language: python
version:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install libcppunit-dev
  - ./install-ola.sh

install:
  - pip install coveralls

script:
  - python -m compileall -f .
  - python manage.py test home
  - coverage run --source=home manage.py test home

after_success: coveralls
