language: python
version:
  - "2.7"

before_install:
  - sudo apt-get update
  - sudo apt-get install libcppunit-dev
  - sudo apt-get install libprotobuf-dev
  - sudo apt-get install libprotoc-dev
  - sudo apt-get install python-protobuf
  - sudo apt-get install python-protobuf.socketrpc
  - pip install protobuf
  - ./install-ola.sh

install:
  - pip install coveralls

script:
#  - python -m compileall -f .
#  - python manage.py test home
#  - coverage run --source=home manage.py test home

after_success: 
#  - coveralls
