language: python
version:
  - "2.7"

install:
  - pip install coveralls

install:
  - git clone https://github.com/stephanmg/ola.git
  - cd ola
  - autoreconf
  - ./configure --enable-python-libs
  - make dist

script:
  - python -m compileall -f .
  - python manage.py test home
  - coverage run --source=home manage.py test home

after_success: coveralls
