language: python

before_script:
  - sudo add-apt-repository ppa:jerome-jblb/ola-ppa -y
  - sudo apt-get update -qq

before_install:
   - sudo apt-get install ola
   - sudo apt-get install ola-python ola-rdm-tests

version:
  - "2.7"

install:
  - pip install coveralls

script:
  - python -m compileall -f .
  - python manage.py test home
  - coverage run --source=home manage.py test home

after_success: coveralls
