language: python

version:
   - "2.7"

before_install:
   - sudo apt-get update
   - sudo apt-get install libcppunit-dev
   - sudo apt-get install libprotobuf-dev
   - sudo apt-get install libprotoc-dev
   - sudo apt-get install python-protobuf
   - sudo apt-get install python-protobuf.socketrpc
   - pip install protobuf
   - pip install coveralls
   - pip install pytest
   - pip install python-coveralls

install:
   - ./install-ola.sh

script:
   -  ./success.sh

script:
  - py.test test/tests.py 

after_success:
  - coveralls
